/* lang.js — WashTime translations. ru / uk / de / en
   Словарь вынесен из index.html отдельным файлом.
   Подключается в <head> ДО основного скрипта — тот использует I18N сразу.
   Все четыре языка должны содержать одинаковый набор ключей: при отсутствии
   перевода t() откатывается на русский.
*/
var I18N = {
  ru: {
    wash:'Стиральная', dry:'Сушильная', dish:'Посудомойка',
    nowBtn:'Сейчас', dataTitle:'Данные', resetStats:'Сбросить статистику',
    delBtn:'Удалить', resetTitle:'Сбросить статистику?',
    machinesTitle:'Машины на экране', visHint:'Запущенная машина показывается всегда',
    exitHint:'Нажмите «назад» ещё раз для выхода',
    durZero:'Длительность не может быть нулевой',
    programsTitle:'Программы', progHint:'Отмеченные ★ показываются на карточке',
    progShowRow:'Показывать на карточке',
    backupSave:'Сохранить настройки', backupSaveSub:'файл в память телефона',
    showConsole:'Показывать консоль', showConsoleSub:'отладочная панель (для разработчика)',
    profileAdd:'+ Новый профиль', profileSaved:'Профиль сохранён',
    remindTitle:'Напоминание', remindOn:'Напомнить о белье',
    tomorrowShort:'завтра',
    langTitle:'🌐 Язык',
    remindSub:'повтор после окончания цикла', remindDelay:'Через',
    remindWash:'🧺 Бельё всё ещё в стиральной машине', remindDry:'🧺 Бельё всё ещё в сушильной машине',
    remindDish:'🍽 Посуда всё ещё в посудомойке',
    backupLoad:'Загрузить настройки', backupLoadSub:'из сохранённого файла',
    backupSaved:'Файл сохранён', backupLoaded:'Настройки загружены',
    backupFail:'Не удалось', backupBad:'Файл не подходит',
    backupLoadTitle:'Загрузить настройки?', backupFrom:'Копия от',
    backupContains:'Профилей / записей:', backupWarn:'Текущие данные будут заменены',
    backupLoadBtn:'Загрузить',
    progNoDur:'не задано', progEmpty:'Программ пока нет',
    progAdd:'+ Добавить', progReset:'Сбросить', progEditTitle:'Программа',
    progName:'Название', progTemp:'°C', progWater:'Вода, л', progKwh:'кВт·ч',
    progNameEmpty:'Введите название', progDelTitle:'Удалить программу?',
    progResetTitle:'Сбросить программы?', progResetText:'Список вернётся к заводскому',
    progResetDone:'Программы сброшены',
    notifTitle:'🔔 Уведомления', notifChannel:'Канал уведомлений',
    pushHowTitle:'Как разрешить уведомления', pushHowTap:'Нажмите, чтобы узнать как →',
    pushHowBrowser:'1. Нажмите на значок 🔒 или ⓘ слева от адреса\n2. Откройте «Настройки сайта» или «Разрешения»\n3. Найдите «Уведомления» и выберите «Разрешить»\n4. Обновите страницу',
    pushHowPwa:'1. Откройте настройки Android\n2. Приложения → WashTime → Уведомления\n3. Включите уведомления\n4. Перезапустите приложение',
    okWord:'Понятно',
    pushAsk:'Нажмите «Разрешить», когда браузер спросит',
    finWashT:'Стирка готова!', finWashS:'Пора вешать бельё',
    finDryT:'Сушка готова!', finDryS:'Бельё высохло',
    finDishT:'Посуда чистая!', finDishS:'Можно доставать',
    familyTitle:'👨‍👩‍👧 Семья', signalTitle:'🔔 Сигнал', melodyClassic:'🎵 Классика',
    melodyDing:'🔔 Дин-дон', melodyFanfare:'🎺 Фанфары', melodySoft:'🎶 Нежная', melodyBeep:'📳 Бип', notifBoth:'📱+✈️ Оба',
    weatherLoading:'Загрузка погоды…',
    photoFromPhone:'📷 Фото с телефона', removePhoto:'Убрать фото', savedWord:'✅ Сохранено:',
    unitL:'л', unitKwh:'кВт·ч', unitKw:'кВт', unitMs:'м/с',
    installHint:'Работает офлайн · Быстрый доступ', installHow:'Как?',
    installIos:'Нажмите  ↑  затем «На экран Домой»',
    pushUnsupported:'⚠️ Push-уведомления не поддерживаются в этом браузере',
    pushAllowed:'✓ Push-уведомления разрешены', pushBlocked:'✗ Push заблокированы. Разрешите в настройках браузера',
    progEco:'Эко', progNormal:'Обычная', progIntensive:'Интенсив', progQuick:'Быстрая',
    progDisinfect:'Дезинфек.', progPre:'Предв.', progSelfClean:'Самоочист.',
    visLast:'Хотя бы одна машина должна остаться',
    resetStatsSub:'история текущего профиля', resetConfirm:'Будет удалена вся история профиля', records:'записей', resetIrrev:'Действие необратимо.',
    resetDone:'Статистика сброшена',
    running:'Работает', waiting:'Ожидание',
    start:'Старт', duration:'Длительность', end:'Конец', remaining:'Осталось',
    signal:'Сигнал по окончанию',
    btnStart:'Запустить', btnStop:'Остановить',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' в ' + at : ''); },
    msgStarted: function(who, what){ return who + ' запустил(а) ' + what; },
    msgStopped: function(who, what){ return who + ' остановил(а) ' + what; },
    washName:'стиральную', dryName:'сушилку', dishName:'посудомойку',
    confirmStop:    function(who, what, time){ return who + ' запустил(а) ' + what + ' в ' + time; },
    confirmStopSub: 'Вы уверены что хотите остановить?',
    confirmNo:'Нет', confirmYes:'Остановить',
    startTime:'Время старта', cancel:'Отмена', done:'Готово',
    profilesTitle:'Профили', male:'♂ Мужчина', female:'♀ Женщина',
    namePlaceholder:'Имя (необязательно)', close:'Закрыть', profileN:'Профиль',
    finishTitle:'Готово!',
    washDone:'Стирка завершена',
    finishBtn:'Отлично! 🎉',
    washMsg:'Стиральная машина готова! 🫧', dryMsg:'Сушильная машина закончила! 💨', dishMsg:'Посудомойка помыла! ✨',
    navMachines:'Машины', navStats:'Статистика', navSettings:'Настройки',
    dryForecast:'🌤 Прогноз сушки', totalRuns:'Всего запусков',
    washes:'🫧 Стирок', dries:'💨 Сушек', dishes:'✨ Мытий',
    thisMonth:'За этот месяц', water:'💧 Вода', electricity:'⚡ Электричество',
    avgTime:'Среднее время', avgLabel:'⏱ Среднее', runsPerMonth:'📅 Запусков в месяц',
    activity7:'Активность за 7 дней', history:'История', historyEmpty:'История пуста',
    weatherLoading:'Загрузка погоды…',
    today:'Сегодня', tomorrow:'Завтра',
    morning:'Утро', day:'День', evening:'Вечер', night:'Ночь',
    bad:'Плохо', ok:'Сойдёт', good:'Отлично',
    familyTitle:'👨‍👩‍👧 Семья', familyCode:'Ваш код семьи',
    familyCodeHint:'Отправьте партнёру — он вставит его ниже', familyCopied:'Код скопирован!',
    familyShareText:'Код семьи WashTime:',
    shareAppBtn:'📲 Поделиться приложением', shareAppText:'WashTime — таймер для стирки, сушки и посуды',
    familyJoinTitle:'Войти в семью', familyJoinHint:'Вставьте код от партнёра', familyJoinBtn:'Войти',
    familyLeaveTitle:'Покинуть семью', familyLeaveHint:'Создаст новый личный код',
    familyLeaveBtn:'Выйти', familyLeaveConfirm:'Покинуть семью?',
    familyLeaveConfirmSub: function(who){ return who + ' отключится от синхронизации. Остальные получат уведомление.'; },
    familyLeft:'Вы покинули семью', familyJoined:'✅ Подключено! Перезагрузите страницу',
    familyInvalidCode:'Введите корректный код',
    memberJoined: function(who){ return who + ' подключился(ась) к семье'; },
    memberLeft:   function(who){ return who + ' покинул(а) семью'; },
    locationTitle:'Местоположение', city:'🌍 Город',
    geoBtn:'📍 Определить автоматически', geoSearching:'🔍 Ищу город…',
    geoNotFound:'❌ Город не найден', geoError:'❌ Ошибка поиска',
    geoUnavailable:'Геолокация недоступна', geoSearching2:'📍 Определяю…',
    myCity:'Мой город', geoDone:'📍 Готово', geoNoAccess:'Нет доступа к геолокации',
    tariffsTitle:'Тарифы', waterRate:'💧 Вода (€/л)', elRate:'⚡ Электричество (€/кВт·ч)',
    save:'Сохранить', saved: function(city){ return '✅ Сохранено: ' + city; },
    aboutTitle:'О приложении', dishData:'Данные посудомойки', dishDataSub:'из инструкции',
    installTitle:'Установить WashTime', installSub:'Добавить на главный экран',
    installBtn:'Установить',
    themeAuto:'🌗 Авто', themeDark:'🌙 Тёмная', themeLight:'☀️ Светлая',
    langLabel:'Язык интерфейса',
    melodyLabel:'Мелодия окончания',
    melodyNames:['🎵 Классика','🔔 Дин-дон','🎺 Фанфары','🎶 Нежная','📳 Бип'], removePhoto:'Убрать фото',
    cropTitle:'Настройте фото', cropScale:'Масштаб', cropHint:'Перетащите для позиции',
  },

  uk: {
    wash:'Пральна', dry:'Сушарка', dish:'Посудомийка',
    nowBtn:'Зараз', dataTitle:'Дані', resetStats:'Скинути статистику',
    delBtn:'Видалити', resetTitle:'Скинути статистику?',
    machinesTitle:'Машини на екрані', visHint:'Запущена машина показується завжди',
    exitHint:'Натисніть «назад» ще раз для виходу',
    durZero:'Тривалість не може бути нульовою',
    programsTitle:'Програми', progHint:'Позначені ★ показуються на картці',
    progShowRow:'Показувати на картці',
    backupSave:'Зберегти налаштування', backupSaveSub:'файл у пам’ять телефона',
    showConsole:'Показувати консоль', showConsoleSub:'панель налагодження (для розробника)',
    profileAdd:'+ Новий профіль', profileSaved:'Профіль збережено',
    remindTitle:'Нагадування', remindOn:'Нагадати про білизну',
    tomorrowShort:'завтра',
    langTitle:'🌐 Мова',
    remindSub:'повтор після завершення циклу', remindDelay:'Через',
    remindWash:'🧺 Білизна досі у пральній машині', remindDry:'🧺 Білизна досі в сушарці',
    remindDish:'🍽 Посуд досі в посудомийці',
    backupLoad:'Завантажити налаштування', backupLoadSub:'зі збереженого файла',
    backupSaved:'Файл збережено', backupLoaded:'Налаштування завантажено',
    backupFail:'Не вдалося', backupBad:'Файл не підходить',
    backupLoadTitle:'Завантажити налаштування?', backupFrom:'Копія від',
    backupContains:'Профілів / записів:', backupWarn:'Поточні дані буде замінено',
    backupLoadBtn:'Завантажити',
    progNoDur:'не задано', progEmpty:'Програм поки немає',
    progAdd:'+ Додати', progReset:'Скинути', progEditTitle:'Програма',
    progName:'Назва', progTemp:'°C', progWater:'Вода, л', progKwh:'кВт·год',
    progNameEmpty:'Введіть назву', progDelTitle:'Видалити програму?',
    progResetTitle:'Скинути програми?', progResetText:'Список повернеться до заводського',
    progResetDone:'Програми скинуто',
    notifTitle:'🔔 Сповіщення', notifChannel:'Канал сповіщень',
    pushHowTitle:'Як дозволити сповіщення', pushHowTap:'Натисніть, щоб дізнатися як →',
    pushHowBrowser:'1. Натисніть на значок 🔒 або ⓘ ліворуч від адреси\n2. Відкрийте «Налаштування сайту» або «Дозволи»\n3. Знайдіть «Сповіщення» і виберіть «Дозволити»\n4. Оновіть сторінку',
    pushHowPwa:'1. Відкрийте налаштування Android\n2. Додатки → WashTime → Сповіщення\n3. Увімкніть сповіщення\n4. Перезапустіть додаток',
    okWord:'Зрозуміло',
    pushAsk:'Натисніть «Дозволити», коли браузер запитає',
    finWashT:'Прання готове!', finWashS:'Час вішати білизну',
    finDryT:'Сушіння готове!', finDryS:'Білизна висохла',
    finDishT:'Посуд чистий!', finDishS:'Можна діставати',
    familyTitle:'👨‍👩‍👧 Родина', signalTitle:'🔔 Сигнал', melodyClassic:'🎵 Класика',
    melodyDing:'🔔 Дін-дон', melodyFanfare:'🎺 Фанфари', melodySoft:'🎶 Ніжна', melodyBeep:'📳 Біп', notifBoth:'📱+✈️ Обидва',
    weatherLoading:'Завантаження погоди…',
    photoFromPhone:'📷 Фото з телефона', removePhoto:'Прибрати фото', savedWord:'✅ Збережено:',
    unitL:'л', unitKwh:'кВт·год', unitKw:'кВт', unitMs:'м/с',
    installHint:'Працює офлайн · Швидкий доступ', installHow:'Як?',
    installIos:'Натисніть  ↑  потім «На екран Домівки»',
    pushUnsupported:'⚠️ Push-сповіщення не підтримуються в цьому браузері',
    pushAllowed:'✓ Push-сповіщення дозволені', pushBlocked:'✗ Push заблоковані. Дозвольте в налаштуваннях браузера',
    progEco:'Еко', progNormal:'Звичайна', progIntensive:'Інтенсив', progQuick:'Швидка',
    progDisinfect:'Дезінфек.', progPre:'Попер.', progSelfClean:'Самоочищ.',
    visLast:'Хоча б одна машина має залишитися',
    resetStatsSub:'історія поточного профілю', resetConfirm:'Буде видалено всю історію профілю', records:'записів', resetIrrev:'Дію неможливо скасувати.',
    resetDone:'Статистику скинуто',
    running:'Працює', waiting:'Очікування',
    start:'Старт', duration:'Тривалість', end:'Кінець', remaining:'Залишилось',
    signal:'Сигнал по завершенню',
    btnStart:'Запустити', btnStop:'Зупинити',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' о ' + at : ''); },
    msgStarted: function(who, what){ return who + ' запустив(ла) ' + what; },
    msgStopped: function(who, what){ return who + ' зупинив(ла) ' + what; },
    washName:'пральну', dryName:'сушарку', dishName:'посудомийку',
    confirmStop:    function(who, what, time){ return who + ' запустив(ла) ' + what + ' о ' + time; },
    confirmStopSub: 'Ви впевнені що хочете зупинити?',
    confirmNo:'Ні', confirmYes:'Зупинити',
    startTime:'Час старту', cancel:'Скасувати', done:'Готово',
    profilesTitle:'Профілі', male:'♂ Чоловік', female:'♀ Жінка',
    namePlaceholder:"Ім'я (необов'язково)", close:'Закрити', profileN:'Профіль',
    finishTitle:'Готово!',
    washDone:'Прання завершено',
    finishBtn:'Чудово! 🎉',
    washMsg:'Пральна машина готова! 🫧', dryMsg:'Сушарка закінчила! 💨', dishMsg:'Посудомийка помила! ✨',
    navMachines:'Машини', navStats:'Статистика', navSettings:'Налаштування',
    dryForecast:'🌤 Прогноз сушіння', totalRuns:'Всього запусків',
    washes:'🫧 Прань', dries:'💨 Сушінь', dishes:'✨ Миттів',
    thisMonth:'За цей місяць', water:'💧 Вода', electricity:'⚡ Електрика',
    avgTime:'Середній час', avgLabel:'⏱ Середнє', runsPerMonth:'📅 Запусків на місяць',
    activity7:'Активність за 7 днів', history:'Історія', historyEmpty:'Історія порожня',
    weatherLoading:'Завантаження погоди…',
    today:'Сьогодні', tomorrow:'Завтра',
    morning:'Ранок', day:'День', evening:'Вечір', night:'Ніч',
    bad:'Погано', ok:'Зійде', good:'Відмінно',
    familyTitle:"👨‍👩‍👧 Сім'я", familyCode:"Ваш код сім'ї",
    familyCodeHint:'Надішліть партнеру — він вставить нижче', familyCopied:'Код скопійовано!',
    familyShareText:'Код родини WashTime:',
    shareAppBtn:'📲 Поділитися застосунком', shareAppText:'WashTime — таймер для прання, сушіння та посуду',
    familyJoinTitle:"Увійти до сім'ї", familyJoinHint:'Вставте код від партнера', familyJoinBtn:'Увійти',
    familyLeaveTitle:"Покинути сім'ю", familyLeaveHint:'Створить новий особистий код',
    familyLeaveBtn:'Вийти', familyLeaveConfirm:"Покинути сім'ю?",
    familyLeaveConfirmSub: function(who){ return who + " відключиться від синхронізації. Інші отримають повідомлення."; },
    familyLeft:"Ви покинули сім'ю", familyJoined:'✅ Підключено! Перезавантажте сторінку',
    familyInvalidCode:'Введіть коректний код',
    memberJoined: function(who){ return who + " підключився(лась) до сім'ї"; },
    memberLeft:   function(who){ return who + " покинув(ла) сім'ю"; },
    locationTitle:'Місцеположення', city:'🌍 Місто',
    geoBtn:'📍 Визначити автоматично', geoSearching:'🔍 Шукаю місто…',
    geoNotFound:'❌ Місто не знайдено', geoError:'❌ Помилка пошуку',
    geoUnavailable:'Геолокація недоступна', geoSearching2:'📍 Визначаю…',
    myCity:'Моє місто', geoDone:'📍 Готово', geoNoAccess:'Немає доступу до геолокації',
    tariffsTitle:'Тарифи', waterRate:'💧 Вода (€/л)', elRate:'⚡ Електрика (€/кВт·г)',
    save:'Зберегти', saved: function(city){ return '✅ Збережено: ' + city; },
    aboutTitle:'Про застосунок', dishData:'Дані посудомийки', dishDataSub:'з інструкції',
    installTitle:'Встановити WashTime', installSub:'Додати на головний екран',
    installBtn:'Встановити',
    themeAuto:'🌗 Авто', themeDark:'🌙 Темна', themeLight:'☀️ Світла',
    langLabel:'Мова інтерфейсу',
    melodyLabel:'Мелодія закінчення',
    melodyNames:['🎵 Класика','🔔 Дзінь-дзінь','🎺 Фанфари','🎶 Ніжна','📳 Біп'], removePhoto:'Видалити фото',
    cropTitle:'Налаштуйте фото', cropScale:'Масштаб', cropHint:'Перетягніть для позиції',
  },

  de: {
    wash:'Waschmaschine', dry:'Trockner', dish:'Spülmaschine',
    nowBtn:'Jetzt', dataTitle:'Daten', resetStats:'Statistik zurücksetzen',
    delBtn:'Löschen', resetTitle:'Statistik zurücksetzen?',
    machinesTitle:'Geräte auf dem Bildschirm', visHint:'Ein laufendes Gerät wird immer angezeigt',
    exitHint:'Zum Beenden erneut „Zurück“ drücken',
    durZero:'Die Dauer darf nicht null sein',
    programsTitle:'Programme', progHint:'Mit ★ markierte erscheinen auf der Karte',
    progShowRow:'Auf der Karte anzeigen',
    backupSave:'Einstellungen sichern', backupSaveSub:'Datei im Telefonspeicher',
    showConsole:'Konsole anzeigen', showConsoleSub:'Debug-Leiste (für Entwickler)',
    profileAdd:'+ Neues Profil', profileSaved:'Profil gespeichert',
    remindTitle:'Erinnerung', remindOn:'An die Wäsche erinnern',
    tomorrowShort:'morgen',
    langTitle:'🌐 Sprache',
    remindSub:'erneut nach Zyklusende', remindDelay:'Nach',
    remindWash:'🧺 Die Wäsche ist noch in der Waschmaschine', remindDry:'🧺 Die Wäsche ist noch im Trockner',
    remindDish:'🍽 Das Geschirr ist noch in der Spülmaschine',
    backupLoad:'Einstellungen laden', backupLoadSub:'aus gesicherter Datei',
    backupSaved:'Datei gespeichert', backupLoaded:'Einstellungen geladen',
    backupFail:'Fehlgeschlagen', backupBad:'Datei passt nicht',
    backupLoadTitle:'Einstellungen laden?', backupFrom:'Sicherung vom',
    backupContains:'Profile / Einträge:', backupWarn:'Aktuelle Daten werden ersetzt',
    backupLoadBtn:'Laden',
    progNoDur:'nicht gesetzt', progEmpty:'Noch keine Programme',
    progAdd:'+ Hinzufügen', progReset:'Zurücksetzen', progEditTitle:'Programm',
    progName:'Name', progTemp:'°C', progWater:'Wasser, l', progKwh:'kWh',
    progNameEmpty:'Bitte Namen eingeben', progDelTitle:'Programm löschen?',
    progResetTitle:'Programme zurücksetzen?', progResetText:'Die Liste wird auf Werkseinstellung gesetzt',
    progResetDone:'Programme zurückgesetzt',
    notifTitle:'🔔 Benachrichtigungen', notifChannel:'Benachrichtigungskanal',
    pushHowTitle:'Benachrichtigungen erlauben', pushHowTap:'Tippen für eine Anleitung →',
    pushHowBrowser:'1. Tippe auf 🔒 oder ⓘ links neben der Adresse\n2. Öffne „Website-Einstellungen“ bzw. „Berechtigungen“\n3. Wähle bei „Benachrichtigungen“ die Option „Zulassen“\n4. Lade die Seite neu',
    pushHowPwa:'1. Öffne die Android-Einstellungen\n2. Apps → WashTime → Benachrichtigungen\n3. Benachrichtigungen aktivieren\n4. App neu starten',
    okWord:'Verstanden',
    pushAsk:'Tippe auf „Erlauben“, wenn der Browser fragt',
    finWashT:'Wäsche fertig!', finWashS:'Zeit zum Aufhängen',
    finDryT:'Trocknen fertig!', finDryS:'Die Wäsche ist trocken',
    finDishT:'Geschirr sauber!', finDishS:'Kann ausgeräumt werden',
    familyTitle:'👨‍👩‍👧 Familie', signalTitle:'🔔 Signal', melodyClassic:'🎵 Klassisch',
    melodyDing:'🔔 Ding-Dong', melodyFanfare:'🎺 Fanfare', melodySoft:'🎶 Sanft', melodyBeep:'📳 Piep', notifBoth:'📱+✈️ Beide',
    weatherLoading:'Wetter wird geladen…',
    photoFromPhone:'📷 Foto vom Handy', removePhoto:'Foto entfernen', savedWord:'✅ Gespeichert:',
    unitL:'l', unitKwh:'kWh', unitKw:'kW', unitMs:'m/s',
    installHint:'Funktioniert offline · Schneller Zugriff', installHow:'Wie?',
    installIos:'Tippe auf  ↑  und dann „Zum Home-Bildschirm“',
    pushUnsupported:'⚠️ Push-Benachrichtigungen werden in diesem Browser nicht unterstützt',
    pushAllowed:'✓ Push-Benachrichtigungen erlaubt', pushBlocked:'✗ Push blockiert. Bitte in den Browsereinstellungen erlauben',
    progEco:'Eco', progNormal:'Normal', progIntensive:'Intensiv', progQuick:'Kurz',
    progDisinfect:'Hygiene', progPre:'Vorspülen', progSelfClean:'Selbstreinigung',
    visLast:'Mindestens ein Gerät muss sichtbar bleiben',
    resetStatsSub:'Verlauf des aktuellen Profils', resetConfirm:'Der gesamte Verlauf des Profils wird gelöscht:', records:'Einträge', resetIrrev:'Dies kann nicht rückgängig gemacht werden.',
    resetDone:'Statistik zurückgesetzt',
    running:'Läuft', waiting:'Wartet',
    start:'Start', duration:'Dauer', end:'Ende', remaining:'Verbleibend',
    signal:'Signal bei Fertigstellung',
    btnStart:'Starten', btnStop:'Stoppen',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' um ' + at : ''); },
    msgStarted: function(who, what){ return who + ' hat ' + what + ' gestartet'; },
    msgStopped: function(who, what){ return who + ' hat ' + what + ' gestoppt'; },
    washName:'die Waschmaschine', dryName:'den Trockner', dishName:'die Spülmaschine',
    confirmStop:    function(who, what, time){ return who + ' hat ' + what + ' um ' + time + ' gestartet'; },
    confirmStopSub: 'Möchten Sie wirklich stoppen?',
    confirmNo:'Nein', confirmYes:'Stoppen',
    startTime:'Startzeit', cancel:'Abbrechen', done:'Fertig',
    profilesTitle:'Profile', male:'♂ Mann', female:'♀ Frau',
    namePlaceholder:'Name (optional)', close:'Schließen', profileN:'Profil',
    finishTitle:'Fertig!',
    washDone:'Wäsche fertig',
    finishBtn:'Super! 🎉',
    washMsg:'Waschmaschine fertig! 🫧', dryMsg:'Trockner fertig! 💨', dishMsg:'Spülmaschine fertig! ✨',
    navMachines:'Maschinen', navStats:'Statistik', navSettings:'Einstellungen',
    dryForecast:'🌤 Trockenprognose', totalRuns:'Starts gesamt',
    washes:'🫧 Wäschen', dries:'💨 Trocknungen', dishes:'✨ Spülgänge',
    thisMonth:'Diesen Monat', water:'💧 Wasser', electricity:'⚡ Strom',
    avgTime:'Durchschnittszeit', avgLabel:'⏱ Schnitt', runsPerMonth:'📅 Starts/Monat',
    activity7:'Aktivität letzte 7 Tage', history:'Verlauf', historyEmpty:'Kein Verlauf',
    weatherLoading:'Wetter wird geladen…',
    today:'Heute', tomorrow:'Morgen',
    morning:'Morgen', day:'Tag', evening:'Abend', night:'Nacht',
    bad:'Schlecht', ok:'Geht so', good:'Sehr gut',
    familyTitle:'👨‍👩‍👧 Familie', familyCode:'Ihr Familiencode',
    familyCodeHint:'An Partner senden — er fügt ihn unten ein', familyCopied:'Code kopiert!',
    familyShareText:'WashTime Familiencode:',
    shareAppBtn:'📲 App teilen', shareAppText:'WashTime — Timer für Wäsche, Trockner und Geschirr',
    familyJoinTitle:'Familie beitreten', familyJoinHint:'Code vom Partner einfügen', familyJoinBtn:'Beitreten',
    familyLeaveTitle:'Familie verlassen', familyLeaveHint:'Erstellt neuen persönlichen Code',
    familyLeaveBtn:'Verlassen', familyLeaveConfirm:'Familie verlassen?',
    familyLeaveConfirmSub: function(who){ return who + ' wird getrennt. Andere werden benachrichtigt.'; },
    familyLeft:'Sie haben die Familie verlassen', familyJoined:'✅ Verbunden! Seite neu laden',
    familyInvalidCode:'Bitte gültigen Code eingeben',
    memberJoined: function(who){ return who + ' ist beigetreten'; },
    memberLeft:   function(who){ return who + ' hat die Familie verlassen'; },
    locationTitle:'Standort', city:'🌍 Stadt',
    geoBtn:'📍 Automatisch bestimmen', geoSearching:'🔍 Suche Stadt…',
    geoNotFound:'❌ Stadt nicht gefunden', geoError:'❌ Suchfehler',
    geoUnavailable:'Geolocation nicht verfügbar', geoSearching2:'📍 Bestimme…',
    myCity:'Meine Stadt', geoDone:'📍 Fertig', geoNoAccess:'Kein Geolocation-Zugriff',
    tariffsTitle:'Tarife', waterRate:'💧 Wasser (€/l)', elRate:'⚡ Strom (€/kWh)',
    save:'Speichern', saved: function(city){ return '✅ Gespeichert: ' + city; },
    aboutTitle:'Über die App', dishData:'Spülmaschinen-Daten', dishDataSub:'aus Anleitung',
    installTitle:'WashTime installieren', installSub:'Zum Startbildschirm hinzufügen',
    installBtn:'Installieren',
    themeAuto:'🌗 Auto', themeDark:'🌙 Dunkel', themeLight:'☀️ Hell',
    langLabel:'Sprache der Oberfläche',
    melodyLabel:'Abschlussmelodie',
    melodyNames:['🎵 Klassisch','🔔 Ding-Dong','🎺 Fanfare','🎶 Sanft','📳 Piep'], removePhoto:'Foto entfernen',
    cropTitle:'Foto anpassen', cropScale:'Zoom', cropHint:'Ziehen für Position',
  },

  en: {
    wash:'Washing Machine', dry:'Dryer', dish:'Dishwasher',
    nowBtn:'Now', dataTitle:'Data', resetStats:'Reset statistics',
    delBtn:'Delete', resetTitle:'Reset statistics?',
    machinesTitle:'Machines on screen', visHint:'A running machine is always shown',
    exitHint:'Press back again to exit',
    durZero:'Duration cannot be zero',
    programsTitle:'Programs', progHint:'Starred ones appear on the card',
    progShowRow:'Show on card',
    backupSave:'Save settings', backupSaveSub:'file in phone storage',
    showConsole:'Show console', showConsoleSub:'debug panel (for developers)',
    profileAdd:'+ New profile', profileSaved:'Profile saved',
    remindTitle:'Reminder', remindOn:'Remind about laundry',
    tomorrowShort:'tomorrow',
    langTitle:'🌐 Language',
    remindSub:'repeat after the cycle ends', remindDelay:'After',
    remindWash:'🧺 The laundry is still in the washer', remindDry:'🧺 The laundry is still in the dryer',
    remindDish:'🍽 The dishes are still in the dishwasher',
    backupLoad:'Load settings', backupLoadSub:'from a saved file',
    backupSaved:'File saved', backupLoaded:'Settings loaded',
    backupFail:'Failed', backupBad:'File not compatible',
    backupLoadTitle:'Load settings?', backupFrom:'Backup from',
    backupContains:'Profiles / records:', backupWarn:'Current data will be replaced',
    backupLoadBtn:'Load',
    progNoDur:'not set', progEmpty:'No programs yet',
    progAdd:'+ Add', progReset:'Reset', progEditTitle:'Program',
    progName:'Name', progTemp:'°C', progWater:'Water, l', progKwh:'kWh',
    progNameEmpty:'Enter a name', progDelTitle:'Delete program?',
    progResetTitle:'Reset programs?', progResetText:'The list returns to factory defaults',
    progResetDone:'Programs reset',
    notifTitle:'🔔 Notifications', notifChannel:'Notification channel',
    pushHowTitle:'How to allow notifications', pushHowTap:'Tap to see how →',
    pushHowBrowser:'1. Tap the 🔒 or ⓘ icon left of the address\n2. Open “Site settings” or “Permissions”\n3. Find “Notifications” and choose “Allow”\n4. Reload the page',
    pushHowPwa:'1. Open Android settings\n2. Apps → WashTime → Notifications\n3. Turn notifications on\n4. Restart the app',
    okWord:'Got it',
    pushAsk:'Tap “Allow” when the browser asks',
    finWashT:'Washing done!', finWashS:'Time to hang it up',
    finDryT:'Drying done!', finDryS:'The laundry is dry',
    finDishT:'Dishes are clean!', finDishS:'Ready to unload',
    familyTitle:'👨‍👩‍👧 Family', signalTitle:'🔔 Signal', melodyClassic:'🎵 Classic',
    melodyDing:'🔔 Ding-dong', melodyFanfare:'🎺 Fanfare', melodySoft:'🎶 Soft', melodyBeep:'📳 Beep', notifBoth:'📱+✈️ Both',
    weatherLoading:'Loading weather…',
    photoFromPhone:'📷 Photo from phone', removePhoto:'Remove photo', savedWord:'✅ Saved:',
    unitL:'l', unitKwh:'kWh', unitKw:'kW', unitMs:'m/s',
    installHint:'Works offline · Quick access', installHow:'How?',
    installIos:'Tap  ↑  then “Add to Home Screen”',
    pushUnsupported:'⚠️ Push notifications are not supported in this browser',
    pushAllowed:'✓ Push notifications allowed', pushBlocked:'✗ Push blocked. Allow it in browser settings',
    progEco:'Eco', progNormal:'Normal', progIntensive:'Intensive', progQuick:'Quick',
    progDisinfect:'Hygiene', progPre:'Pre-rinse', progSelfClean:'Self-clean',
    visLast:'At least one machine must stay visible',
    resetStatsSub:'current profile history', resetConfirm:'All history will be deleted for profile', records:'records', resetIrrev:'This cannot be undone.',
    resetDone:'Statistics reset',
    running:'Running', waiting:'Waiting',
    start:'Start', duration:'Duration', end:'End', remaining:'Remaining',
    signal:'Signal on finish',
    btnStart:'Start', btnStop:'Stop',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' at ' + at : ''); },
    msgStarted: function(who, what){ return who + ' started ' + what; },
    msgStopped: function(who, what){ return who + ' stopped ' + what; },
    washName:'the washer', dryName:'the dryer', dishName:'the dishwasher',
    confirmStop:    function(who, what, time){ return who + ' started ' + what + ' at ' + time; },
    confirmStopSub: 'Are you sure you want to stop?',
    confirmNo:'No', confirmYes:'Stop',
    startTime:'Start Time', cancel:'Cancel', done:'Done',
    profilesTitle:'Profiles', male:'♂ Male', female:'♀ Female',
    namePlaceholder:'Name (optional)', close:'Close', profileN:'Profile',
    finishTitle:'Done!',
    washDone:'Washing complete',
    finishBtn:'Great! 🎉',
    washMsg:'Washing machine done! 🫧', dryMsg:'Dryer done! 💨', dishMsg:'Dishwasher done! ✨',
    navMachines:'Machines', navStats:'Statistics', navSettings:'Settings',
    dryForecast:'🌤 Drying Forecast', totalRuns:'Total runs',
    washes:'🫧 Washes', dries:'💨 Drying', dishes:'✨ Dishwashing',
    thisMonth:'This month', water:'💧 Water', electricity:'⚡ Electricity',
    avgTime:'Average time', avgLabel:'⏱ Average', runsPerMonth:'📅 Runs/month',
    activity7:'Activity last 7 days', history:'History', historyEmpty:'No history yet',
    weatherLoading:'Loading weather…',
    today:'Today', tomorrow:'Tomorrow',
    morning:'Morning', day:'Day', evening:'Evening', night:'Night',
    bad:'Bad', ok:'Okay', good:'Great',
    familyTitle:'👨‍👩‍👧 Family', familyCode:'Your family code',
    familyCodeHint:'Send to your partner — they paste it below', familyCopied:'Code copied!',
    familyShareText:'WashTime family code:',
    shareAppBtn:'📲 Share the app', shareAppText:'WashTime — a timer for laundry, dryer and dishes',
    familyJoinTitle:'Join family', familyJoinHint:'Paste code from your partner', familyJoinBtn:'Join',
    familyLeaveTitle:'Leave family', familyLeaveHint:'Creates a new personal code',
    familyLeaveBtn:'Leave', familyLeaveConfirm:'Leave family?',
    familyLeaveConfirmSub: function(who){ return who + ' will disconnect. Others will be notified.'; },
    familyLeft:'You left the family', familyJoined:'✅ Connected! Reload the page',
    familyInvalidCode:'Please enter a valid code',
    memberJoined: function(who){ return who + ' joined the family'; },
    memberLeft:   function(who){ return who + ' left the family'; },
    locationTitle:'Location', city:'🌍 City',
    geoBtn:'📍 Detect automatically', geoSearching:'🔍 Searching city…',
    geoNotFound:'❌ City not found', geoError:'❌ Search error',
    geoUnavailable:'Geolocation unavailable', geoSearching2:'📍 Detecting…',
    myCity:'My city', geoDone:'📍 Done', geoNoAccess:'No geolocation access',
    tariffsTitle:'Tariffs', waterRate:'💧 Water (€/l)', elRate:'⚡ Electricity (€/kWh)',
    save:'Save', saved: function(city){ return '✅ Saved: ' + city; },
    aboutTitle:'About', dishData:'Dishwasher data', dishDataSub:'from manual',
    installTitle:'Install WashTime', installSub:'Add to home screen',
    installBtn:'Install',
    themeAuto:'🌗 Auto', themeDark:'🌙 Dark', themeLight:'☀️ Light',
    langLabel:'Interface language',
    melodyLabel:'Finish melody',
    melodyNames:['🎵 Classic','🔔 Ding-dong','🎺 Fanfare','🎶 Gentle','📳 Beep'], removePhoto:'Remove photo',
    cropTitle:'Adjust photo', cropScale:'Scale', cropHint:'Drag to position',
  }
};
