/* lang.js — WashTime translations. ru / uk / de / en */
var I18N = {
  ru: {
    wash:'Стиральная', dry:'Сушильная', dish:'Посудомойка',
    running:'Работает', waiting:'Ожидание',
    start:'Старт', duration:'Длительность', end:'Конец', remaining:'Осталось',
    signal:'Сигнал по окончанию',
    btnStart:'Запустить', btnStop:'Остановить',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' в ' + at : ''); },
    msgStarted: function(who, what){ return who + ' запустил(а) ' + what; },
    msgStopped: function(who, what){ return who + ' остановил(а) ' + what; },
    washName:'стиральную', dryName:'сушилку', dishName:'посудомойку',
    confirmStop:    function(who, what, time){ return who + ' запустил(а) ' + what + ' в ' + time; },
    confirmStopSub: 'Вы уверены что хотите остановить?',
    confirmNo:'Нет', confirmYes:'Остановить',
    startTime:'Время старта', cancel:'Отмена', done:'Готово',
    profilesTitle:'Профили', male:'♂ Мужчина', female:'♀ Женщина',
    namePlaceholder:'Имя (необязательно)', close:'Закрыть', profileN:'Профиль',
    finishTitle:'Готово!',
    washDone:'Стирка завершена', dryDone:'Сушка завершена', dishDone:'Посуда чистая!',
    finishBtn:'Отлично! 🎉',
    washMsg:'Стиральная машина готова! 🫧', dryMsg:'Сушильная машина закончила! 💨', dishMsg:'Посудомойка помыла! ✨',
    navMachines:'Машины', navStats:'Статистика', navSettings:'Настройки',
    dryForecast:'🌤 Прогноз сушки', totalRuns:'Всего запусков',
    washes:'🫧 Стирок', dries:'💨 Сушек', dishes:'✨ Мытий',
    thisMonth:'За этот месяц', water:'💧 Вода', electricity:'⚡ Электричество',
    avgTime:'Среднее время', avgLabel:'⏱ Среднее', runsPerMonth:'📅 Запусков в месяц',
    activity7:'Активность за 7 дней', history:'История', historyEmpty:'История пуста',
    weatherLoading:'Загрузка погоды…', weatherError:'Не удалось загрузить погоду',
    today:'Сегодня', tomorrow:'Завтра',
    morning:'Утро', day:'День', evening:'Вечер', night:'Ночь',
    bad:'Плохо', ok:'Сойдёт', good:'Отлично',
    familyTitle:'👨‍👩‍👧 Семья', familyCode:'Ваш код семьи',
    familyCodeHint:'Отправьте партнёру — он вставит его ниже',
    familyCopy:'📋 Копировать', familyCopied:'Код скопирован!',
    familyJoinTitle:'Войти в семью', familyJoinHint:'Вставьте код от партнёра',
    familyJoinPlaceholder:'family_xxxxxxxx', familyJoinBtn:'Войти',
    familyLeaveTitle:'Покинуть семью', familyLeaveHint:'Создаст новый личный код',
    familyLeaveBtn:'Выйти', familyLeaveConfirm:'Покинуть семью?',
    familyLeaveConfirmSub: function(who){ return who + ' отключится от синхронизации. Остальные получат уведомление.'; },
    familyLeft:'Вы покинули семью', familyJoined:'✅ Подключено! Перезагрузите страницу',
    familyInvalidCode:'Введите корректный код',
    memberJoined: function(who){ return who + ' подключился(ась) к семье'; },
    memberLeft:   function(who){ return who + ' покинул(а) семью'; },
    locationTitle:'Местоположение', city:'🌍 Город', cityPlaceholder:'Oberhausen',
    geoBtn:'📍 Определить автоматически', geoSearching:'🔍 Ищу город…',
    geoNotFound:'❌ Город не найден', geoError:'❌ Ошибка поиска',
    geoUnavailable:'Геолокация недоступна', geoSearching2:'📍 Определяю…',
    myCity:'Мой город', geoDone:'📍 Готово', geoNoAccess:'Нет доступа к геолокации',
    tariffsTitle:'Тарифы', waterRate:'💧 Вода (€/л)', elRate:'⚡ Электричество (€/кВт·ч)',
    save:'Сохранить', saved: function(city){ return '✅ Сохранено: ' + city; },
    aboutTitle:'О приложении', dishData:'Данные посудомойки', dishDataSub:'из инструкции',
    installTitle:'Установить WashTime', installSub:'Добавить на главный экран',
    installBtn:'Установить', installOffline:'Работает офлайн · Быстрый доступ',
    iosInstallTitle:'Установка на iPhone',
    iosStep1:'Нажмите <strong>«Поделиться»</strong> (↑) внизу Safari',
    iosStep2:'Выберите <strong>«На экран Домой»</strong>',
    iosStep3:'Нажмите <strong>«Добавить»</strong>',
    iosHow:'Как?', iosUnderstood:'Понятно',
    themeAuto:'🌗 Авто', themeDark:'🌙 Тёмная', themeLight:'☀️ Светлая',
    langTitle:'🌐 Язык',
    langLabel:'Язык интерфейса',
    melodyLabel:'Мелодия окончания',
    melodyNames:['🎵 Классика','🔔 Дин-дон','🎺 Фанфары','🎶 Нежная','📳 Бип'],
    photoBtn:'📷 Фото', removePhoto:'Убрать фото',
    cropTitle:'Настройте фото', cropScale:'Масштаб', cropHint:'Перетащите для позиции',
  },

  uk: {
    wash:'Пральна', dry:'Сушарка', dish:'Посудомийка',
    running:'Працює', waiting:'Очікування',
    start:'Старт', duration:'Тривалість', end:'Кінець', remaining:'Залишилось',
    signal:'Сигнал по завершенню',
    btnStart:'Запустити', btnStop:'Зупинити',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' о ' + at : ''); },
    msgStarted: function(who, what){ return who + ' запустив(ла) ' + what; },
    msgStopped: function(who, what){ return who + ' зупинив(ла) ' + what; },
    washName:'пральну', dryName:'сушарку', dishName:'посудомийку',
    confirmStop:    function(who, what, time){ return who + ' запустив(ла) ' + what + ' о ' + time; },
    confirmStopSub: 'Ви впевнені що хочете зупинити?',
    confirmNo:'Ні', confirmYes:'Зупинити',
    startTime:'Час старту', cancel:'Скасувати', done:'Готово',
    profilesTitle:'Профілі', male:'♂ Чоловік', female:'♀ Жінка',
    namePlaceholder:"Ім'я (необов'язково)", close:'Закрити', profileN:'Профіль',
    finishTitle:'Готово!',
    washDone:'Прання завершено', dryDone:'Сушіння завершено', dishDone:'Посуд чистий!',
    finishBtn:'Чудово! 🎉',
    washMsg:'Пральна машина готова! 🫧', dryMsg:'Сушарка закінчила! 💨', dishMsg:'Посудомийка помила! ✨',
    navMachines:'Машини', navStats:'Статистика', navSettings:'Налаштування',
    dryForecast:'🌤 Прогноз сушіння', totalRuns:'Всього запусків',
    washes:'🫧 Прань', dries:'💨 Сушінь', dishes:'✨ Миттів',
    thisMonth:'За цей місяць', water:'💧 Вода', electricity:'⚡ Електрика',
    avgTime:'Середній час', avgLabel:'⏱ Середнє', runsPerMonth:'📅 Запусків на місяць',
    activity7:'Активність за 7 днів', history:'Історія', historyEmpty:'Історія порожня',
    weatherLoading:'Завантаження погоди…', weatherError:'Не вдалося завантажити погоду',
    today:'Сьогодні', tomorrow:'Завтра',
    morning:'Ранок', day:'День', evening:'Вечір', night:'Ніч',
    bad:'Погано', ok:'Зійде', good:'Відмінно',
    familyTitle:"👨‍👩‍👧 Сім'я", familyCode:"Ваш код сім'ї",
    familyCodeHint:'Надішліть партнеру — він вставить нижче',
    familyCopy:'📋 Копіювати', familyCopied:'Код скопійовано!',
    familyJoinTitle:"Увійти до сім'ї", familyJoinHint:'Вставте код від партнера',
    familyJoinPlaceholder:'family_xxxxxxxx', familyJoinBtn:'Увійти',
    familyLeaveTitle:"Покинути сім'ю", familyLeaveHint:'Створить новий особистий код',
    familyLeaveBtn:'Вийти', familyLeaveConfirm:"Покинути сім'ю?",
    familyLeaveConfirmSub: function(who){ return who + " відключиться від синхронізації. Інші отримають повідомлення."; },
    familyLeft:"Ви покинули сім'ю", familyJoined:'✅ Підключено! Перезавантажте сторінку',
    familyInvalidCode:'Введіть коректний код',
    memberJoined: function(who){ return who + " підключився(лась) до сім'ї"; },
    memberLeft:   function(who){ return who + " покинув(ла) сім'ю"; },
    locationTitle:'Місцеположення', city:'🌍 Місто', cityPlaceholder:'Oberhausen',
    geoBtn:'📍 Визначити автоматично', geoSearching:'🔍 Шукаю місто…',
    geoNotFound:'❌ Місто не знайдено', geoError:'❌ Помилка пошуку',
    geoUnavailable:'Геолокація недоступна', geoSearching2:'📍 Визначаю…',
    myCity:'Моє місто', geoDone:'📍 Готово', geoNoAccess:'Немає доступу до геолокації',
    tariffsTitle:'Тарифи', waterRate:'💧 Вода (€/л)', elRate:'⚡ Електрика (€/кВт·г)',
    save:'Зберегти', saved: function(city){ return '✅ Збережено: ' + city; },
    aboutTitle:'Про застосунок', dishData:'Дані посудомийки', dishDataSub:'з інструкції',
    installTitle:'Встановити WashTime', installSub:'Додати на головний екран',
    installBtn:'Встановити', installOffline:'Працює офлайн · Швидкий доступ',
    iosInstallTitle:'Встановлення на iPhone',
    iosStep1:'Натисніть <strong>«Поділитись»</strong> (↑) внизу Safari',
    iosStep2:'Виберіть <strong>«На головний екран»</strong>',
    iosStep3:"Натисніть <strong>«Додати»</strong>",
    iosHow:'Як?', iosUnderstood:'Зрозуміло',
    themeAuto:'🌗 Авто', themeDark:'🌙 Темна', themeLight:'☀️ Світла',
    langTitle:'🌐 Мова',
    langLabel:'Мова інтерфейсу',
    melodyLabel:'Мелодія закінчення',
    melodyNames:['🎵 Класика','🔔 Дзінь-дзінь','🎺 Фанфари','🎶 Ніжна','📳 Біп'],
    photoBtn:'📷 Фото', removePhoto:'Видалити фото',
    cropTitle:'Налаштуйте фото', cropScale:'Масштаб', cropHint:'Перетягніть для позиції',
  },

  de: {
    wash:'Waschmaschine', dry:'Trockner', dish:'Spülmaschine',
    running:'Läuft', waiting:'Wartet',
    start:'Start', duration:'Dauer', end:'Ende', remaining:'Verbleibend',
    signal:'Signal bei Fertigstellung',
    btnStart:'Starten', btnStop:'Stoppen',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' um ' + at : ''); },
    msgStarted: function(who, what){ return who + ' hat ' + what + ' gestartet'; },
    msgStopped: function(who, what){ return who + ' hat ' + what + ' gestoppt'; },
    washName:'die Waschmaschine', dryName:'den Trockner', dishName:'die Spülmaschine',
    confirmStop:    function(who, what, time){ return who + ' hat ' + what + ' um ' + time + ' gestartet'; },
    confirmStopSub: 'Möchten Sie wirklich stoppen?',
    confirmNo:'Nein', confirmYes:'Stoppen',
    startTime:'Startzeit', cancel:'Abbrechen', done:'Fertig',
    profilesTitle:'Profile', male:'♂ Mann', female:'♀ Frau',
    namePlaceholder:'Name (optional)', close:'Schließen', profileN:'Profil',
    finishTitle:'Fertig!',
    washDone:'Wäsche fertig', dryDone:'Trocknen fertig', dishDone:'Geschirr sauber!',
    finishBtn:'Super! 🎉',
    washMsg:'Waschmaschine fertig! 🫧', dryMsg:'Trockner fertig! 💨', dishMsg:'Spülmaschine fertig! ✨',
    navMachines:'Maschinen', navStats:'Statistik', navSettings:'Einstellungen',
    dryForecast:'🌤 Trockenprognose', totalRuns:'Starts gesamt',
    washes:'🫧 Wäschen', dries:'💨 Trocknungen', dishes:'✨ Spülgänge',
    thisMonth:'Diesen Monat', water:'💧 Wasser', electricity:'⚡ Strom',
    avgTime:'Durchschnittszeit', avgLabel:'⏱ Schnitt', runsPerMonth:'📅 Starts/Monat',
    activity7:'Aktivität letzte 7 Tage', history:'Verlauf', historyEmpty:'Kein Verlauf',
    weatherLoading:'Wetter wird geladen…', weatherError:'Wetter nicht verfügbar',
    today:'Heute', tomorrow:'Morgen',
    morning:'Morgen', day:'Tag', evening:'Abend', night:'Nacht',
    bad:'Schlecht', ok:'Geht so', good:'Sehr gut',
    familyTitle:'👨‍👩‍👧 Familie', familyCode:'Ihr Familiencode',
    familyCodeHint:'An Partner senden — er fügt ihn unten ein',
    familyCopy:'📋 Kopieren', familyCopied:'Code kopiert!',
    familyJoinTitle:'Familie beitreten', familyJoinHint:'Code vom Partner einfügen',
    familyJoinPlaceholder:'family_xxxxxxxx', familyJoinBtn:'Beitreten',
    familyLeaveTitle:'Familie verlassen', familyLeaveHint:'Erstellt neuen persönlichen Code',
    familyLeaveBtn:'Verlassen', familyLeaveConfirm:'Familie verlassen?',
    familyLeaveConfirmSub: function(who){ return who + ' wird getrennt. Andere werden benachrichtigt.'; },
    familyLeft:'Sie haben die Familie verlassen', familyJoined:'✅ Verbunden! Seite neu laden',
    familyInvalidCode:'Bitte gültigen Code eingeben',
    memberJoined: function(who){ return who + ' ist beigetreten'; },
    memberLeft:   function(who){ return who + ' hat die Familie verlassen'; },
    locationTitle:'Standort', city:'🌍 Stadt', cityPlaceholder:'Oberhausen',
    geoBtn:'📍 Automatisch bestimmen', geoSearching:'🔍 Suche Stadt…',
    geoNotFound:'❌ Stadt nicht gefunden', geoError:'❌ Suchfehler',
    geoUnavailable:'Geolocation nicht verfügbar', geoSearching2:'📍 Bestimme…',
    myCity:'Meine Stadt', geoDone:'📍 Fertig', geoNoAccess:'Kein Geolocation-Zugriff',
    tariffsTitle:'Tarife', waterRate:'💧 Wasser (€/l)', elRate:'⚡ Strom (€/kWh)',
    save:'Speichern', saved: function(city){ return '✅ Gespeichert: ' + city; },
    aboutTitle:'Über die App', dishData:'Spülmaschinen-Daten', dishDataSub:'aus Anleitung',
    installTitle:'WashTime installieren', installSub:'Zum Startbildschirm hinzufügen',
    installBtn:'Installieren', installOffline:'Offline verfügbar · Schneller Zugriff',
    iosInstallTitle:'Installation auf iPhone',
    iosStep1:'Tippen Sie auf <strong>«Teilen»</strong> (↑) in Safari',
    iosStep2:'Wählen Sie <strong>«Zum Home-Bildschirm»</strong>',
    iosStep3:'Tippen Sie auf <strong>«Hinzufügen»</strong>',
    iosHow:'Wie?', iosUnderstood:'Verstanden',
    themeAuto:'🌗 Auto', themeDark:'🌙 Dunkel', themeLight:'☀️ Hell',
    langTitle:'🌐 Sprache',
    langLabel:'Sprache der Oberfläche',
    melodyLabel:'Abschlussmelodie',
    melodyNames:['🎵 Klassisch','🔔 Ding-Dong','🎺 Fanfare','🎶 Sanft','📳 Piep'],
    photoBtn:'📷 Foto', removePhoto:'Foto entfernen',
    cropTitle:'Foto anpassen', cropScale:'Zoom', cropHint:'Ziehen für Position',
  },

  en: {
    wash:'Washing Machine', dry:'Dryer', dish:'Dishwasher',
    running:'Running', waiting:'Waiting',
    start:'Start', duration:'Duration', end:'End', remaining:'Remaining',
    signal:'Signal on finish',
    btnStart:'Start', btnStop:'Stop',
    launchedBy: function(who){ return '▶ ' + who; },
    stoppedBy:  function(who, at){ return '⏹ ' + who + (at ? ' at ' + at : ''); },
    msgStarted: function(who, what){ return who + ' started ' + what; },
    msgStopped: function(who, what){ return who + ' stopped ' + what; },
    washName:'the washer', dryName:'the dryer', dishName:'the dishwasher',
    confirmStop:    function(who, what, time){ return who + ' started ' + what + ' at ' + time; },
    confirmStopSub: 'Are you sure you want to stop?',
    confirmNo:'No', confirmYes:'Stop',
    startTime:'Start Time', cancel:'Cancel', done:'Done',
    profilesTitle:'Profiles', male:'♂ Male', female:'♀ Female',
    namePlaceholder:'Name (optional)', close:'Close', profileN:'Profile',
    finishTitle:'Done!',
    washDone:'Washing complete', dryDone:'Drying complete', dishDone:'Dishes clean!',
    finishBtn:'Great! 🎉',
    washMsg:'Washing machine done! 🫧', dryMsg:'Dryer done! 💨', dishMsg:'Dishwasher done! ✨',
    navMachines:'Machines', navStats:'Statistics', navSettings:'Settings',
    dryForecast:'🌤 Drying Forecast', totalRuns:'Total runs',
    washes:'🫧 Washes', dries:'💨 Drying', dishes:'✨ Dishwashing',
    thisMonth:'This month', water:'💧 Water', electricity:'⚡ Electricity',
    avgTime:'Average time', avgLabel:'⏱ Average', runsPerMonth:'📅 Runs/month',
    activity7:'Activity last 7 days', history:'History', historyEmpty:'No history yet',
    weatherLoading:'Loading weather…', weatherError:'Could not load weather',
    today:'Today', tomorrow:'Tomorrow',
    morning:'Morning', day:'Day', evening:'Evening', night:'Night',
    bad:'Bad', ok:'Okay', good:'Great',
    familyTitle:'👨‍👩‍👧 Family', familyCode:'Your family code',
    familyCodeHint:'Send to your partner — they paste it below',
    familyCopy:'📋 Copy', familyCopied:'Code copied!',
    familyJoinTitle:'Join family', familyJoinHint:'Paste code from your partner',
    familyJoinPlaceholder:'family_xxxxxxxx', familyJoinBtn:'Join',
    familyLeaveTitle:'Leave family', familyLeaveHint:'Creates a new personal code',
    familyLeaveBtn:'Leave', familyLeaveConfirm:'Leave family?',
    familyLeaveConfirmSub: function(who){ return who + ' will disconnect. Others will be notified.'; },
    familyLeft:'You left the family', familyJoined:'✅ Connected! Reload the page',
    familyInvalidCode:'Please enter a valid code',
    memberJoined: function(who){ return who + ' joined the family'; },
    memberLeft:   function(who){ return who + ' left the family'; },
    locationTitle:'Location', city:'🌍 City', cityPlaceholder:'Oberhausen',
    geoBtn:'📍 Detect automatically', geoSearching:'🔍 Searching city…',
    geoNotFound:'❌ City not found', geoError:'❌ Search error',
    geoUnavailable:'Geolocation unavailable', geoSearching2:'📍 Detecting…',
    myCity:'My city', geoDone:'📍 Done', geoNoAccess:'No geolocation access',
    tariffsTitle:'Tariffs', waterRate:'💧 Water (€/l)', elRate:'⚡ Electricity (€/kWh)',
    save:'Save', saved: function(city){ return '✅ Saved: ' + city; },
    aboutTitle:'About', dishData:'Dishwasher data', dishDataSub:'from manual',
    installTitle:'Install WashTime', installSub:'Add to home screen',
    installBtn:'Install', installOffline:'Works offline · Quick access',
    iosInstallTitle:'Install on iPhone',
    iosStep1:'Tap <strong>«Share»</strong> (↑) at the bottom of Safari',
    iosStep2:'Select <strong>«Add to Home Screen»</strong>',
    iosStep3:'Tap <strong>«Add»</strong>',
    iosHow:'How?', iosUnderstood:'Got it',
    themeAuto:'🌗 Auto', themeDark:'🌙 Dark', themeLight:'☀️ Light',
    langTitle:'🌐 Language',
    langLabel:'Interface language',
    melodyLabel:'Finish melody',
    melodyNames:['🎵 Classic','🔔 Ding-dong','🎺 Fanfare','🎶 Gentle','📳 Beep'],
    photoBtn:'📷 Photo', removePhoto:'Remove photo',
    cropTitle:'Adjust photo', cropScale:'Scale', cropHint:'Drag to position',
  }
};

function detectLang() {
  // Системный язык телефона
  var sys = (navigator.language || navigator.userLanguage || 'ru').slice(0, 2).toLowerCase();
  var sysLang = I18N[sys] ? sys : 'ru';

  // Пользователь явно выбрал язык вручную — уважаем выбор
  var userPicked = localStorage.getItem('washLangManual');
  if (userPicked && I18N[userPicked]) return userPicked;

  // Иначе — системный язык
  return sysLang;
}

var LANG = detectLang();

function t(key) {
  var args = Array.prototype.slice.call(arguments, 1);
  var dict = I18N[LANG] || I18N.ru;
  var val = (dict[key] !== undefined) ? dict[key] : (I18N.ru[key] !== undefined ? I18N.ru[key] : key);
  return typeof val === 'function' ? val.apply(null, args) : val;
}


function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    var val = t(key);
    if (val && val !== key) el.textContent = val;
  });
  // Навбар — у span внутри button
  var sel = document.getElementById('langSelect');
  if (sel) sel.value = LANG;
}

function setLang(lang) {
  if (!I18N[lang]) return;
  LANG = lang;
  localStorage.setItem('washLangManual', lang); // ручной выбор пользователя
  applyI18n();
  if (typeof buildSlides === 'function') buildSlides();
  if (typeof renderStats === 'function') renderStats();
  if (typeof renderHist === 'function') renderHist();
  if (typeof renderProfileBar === 'function') renderProfileBar();
}
